name: Publish Package

on:
  workflow_dispatch:
  # Alternatively, trigger on release events:
  # release:
  #   types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build
        # Remove this step if your package doesn't require a build step

      - name: Publish Package
        run: npm publish
